import html2pdf from "html2pdf.js";
import Template1 from "../Templates/Template1";
import Template2 from "../Templates/Template2";
import TraditionalTemplate from "../Templates/TraditionalTemplate";

function BiodataPreview({ formData, isGuest, template, privacy, fontStyle, accentColor }) {

  const downloadPDF = () => {
    const element = document.getElementById("biodata-preview-wrapper");
    const options = {
      margin:      0,
      filename:    "ShaadiBio-Biodata.pdf",
      image:       { type: "jpeg", quality: 0.98 },
      html2canvas: { scale: 2, useCORS: true },
      jsPDF:       { unit: "mm", format: "a4", orientation: "portrait" }
    };
    html2pdf().set(options).from(element).save();
  };

  const fontFamily =
    fontStyle === "sans"       ? "Jost, sans-serif" :
    fontStyle === "decorative" ? "Cinzel Decorative, cursive" :
                                 "Cormorant Garamond, serif";

  return (
    <div>

      {/* Preview wrapper */}
      <div id="biodata-preview-wrapper" style={{ position: "relative" }}>

        {/* Watermark for guest users */}
        {isGuest && (
          <div style={{
            position: "absolute",
            inset: 0,
            zIndex: 10,
            pointerEvents: "none",
            overflow: "hidden",
            display: "flex",
            flexDirection: "column",
            alignItems: "center",
            justifyContent: "space-around",
            gap: "40px",
            padding: "40px 0",
          }}>
            {[...Array(8)].map((_, i) => (
              <div key={i} style={{
                fontFamily: "Jost, sans-serif",
                fontSize: "20px",
                fontWeight: "700",
                color: "rgba(233, 30, 140, 0.13)",
                transform: "rotate(-35deg)",
                whiteSpace: "nowrap",
                letterSpacing: "4px",
                textTransform: "uppercase",
                userSelect: "none",
              }}>
                Generated by ShaadiBio
              </div>
            ))}
          </div>
        )}

        {/* Biodata Template with font + color applied */}
        <div id="biodata-preview" style={{ fontFamily }}>
          {template === "modern" && (
            <Template1
              formData={formData}
              privacy={privacy}
              accentColor={accentColor}
            />
          )}
          {template === "mughal" && (
            <Template2
              formData={formData}
              privacy={privacy}
              accentColor={accentColor}
            />
          )}
          {template === "traditional" && (
            <TraditionalTemplate
              formData={formData}
              privacy={privacy}
              accentColor={accentColor}
            />
          )}
        </div>

      </div>

      {/* Download Button */}
      <div style={{ textAlign: "center", marginTop: "20px" }}>
        <button
          onClick={downloadPDF}
          style={{
            padding: "12px 36px",
            background: "linear-gradient(135deg, #1A1A2E, " + (accentColor || "#E91E8C") + ")",
            color: "white",
            border: "none",
            borderRadius: "8px",
            fontFamily: "Jost, sans-serif",
            fontSize: "15px",
            fontWeight: "600",
            cursor: "pointer",
            letterSpacing: "0.5px",
          }}
        >
          Download PDF
        </button>
      </div>

    </div>
  );
}

export default BiodataPreview;